name: Greeting from testland
on: push
jobs:
  my-job:
    runs-on: ubuntu-18.04
    name: Truffle testing trial
    steps:
      - uses: actions/checkout@master
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node }}
      - run: sudo npm install -g truffle ganache-cli
      - run: sudo ganache-cli & truffle test
